# Generated by Django 4.0.5 on 2022-07-25 00:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('ingredients', models.TextField(verbose_name='Ingredientes')),
                ('method_preparation', models.TextField(verbose_name='Modo de preparo')),
                ('cooking_time', models.IntegerField(verbose_name='Tempo de preparo')),
                ('recipe_yield', models.CharField(max_length=100, verbose_name='Rendimento')),
                ('category', models.CharField(max_length=100, verbose_name='Categoria')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Criado em')),
            ],
        ),
    ]
